#!/usr/bin/env python3
import sys
from PyQt5.QtWidgets import QApplication, QWidget, QDesktopWidget
from PyQt5 import QtCore, QtGui, QtWidgets
sys.path.insert(1, './')
from Functions_hitb import frame1, grid

class MainWindow(QWidget):

    def __init__(self):
        super().__init__()
        self.initUI()

    def initUI(self):
        self.setWindowTitle('Hack-In-The-Box')
        self.setFixedHeight(650)
        self.setFixedWidth(1000)
        self.setStyleSheet('background: #161219;')
        frame1()
        self.setLayout(grid)
        self.center()
        self.show()

    def center(self):
        qr = self.frameGeometry()
        cp = QDesktopWidget().availableGeometry().center()
        qr.moveCenter(cp)
        self.move(qr.topLeft())

if __name__ == '__main__':
    app = QApplication(sys.argv)
    ex = MainWindow()
    sys.exit(app.exec_())
