#!/usr/bin/env python3
import sys
from PyQt5 import QtCore, QtGui, QtWidgets
import subprocess

class Terminal(QtWidgets.QWidget):
    def __init__(self):
        super().__init__()

        self.output = QtWidgets.QTextEdit(self)
        self.output.setReadOnly(True)
        self.input = QtWidgets.QLineEdit(self)

        self.layout = QtWidgets.QVBoxLayout(self)
        self.layout.addWidget(self.output)
        self.layout.addWidget(self.input)

        self.input.returnPressed.connect(self.run_command)

    def run_command(self):
        command = self.input.text()
        self.input.clear()
        self.output.append(f'$ {command}')
        self.process = QtCore.QProcess(self)
        self.process.readyReadStandardOutput.connect(self.readOutput)
        self.process.start(command)

    def readOutput(self):
        output = str(self.process.readAllStandardOutput(), 'utf-8')
        self.output.append(output)


if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    terminal = Terminal()
    terminal.show()
    sys.exit(app.exec_())
